### ISSUE TITLE
Jekyll migration discussion

### ISSUE THREAD

**Issue by Visgean** [qaisjp/inf1.hgs.club#11]
migrate this to jekyll so that each section can be markdown file

**Comment by neanias** [comment]
Something something Better Informatics

**Comment by Visgean** [comment]
Sure. thats the point - so that the migration of this content will be easy..

**Comment by neanias** [comment]
Something something pandoc

**Comment by qaisjp** [comment]
Yes!

**Comment by neanias** [comment]
Simply having a wonder-jekyll time

**Comment by qaisjp** [comment]
[Some progress has been made](https://github.com/qaisjp/inf1.hgs.club/compare/9ece29d3c8fa8196706677927a2e6aeed5c5d596...78ad68969562854b68dbb6df864d165de47c74b9)

please share your thoughts
