### ISSUE TITLE
add section "Finding a flat"

### ISSUE THREAD

**Issue by Visgean** [qaisjp/inf1.hgs.club#14]
there are some good articles and resources and overall the market in Edinburgh is specific so I think its good idea to share links here.

**Comment by qaisjp** [comment]
please provide links and information for this and one of us can create the section :)

**Comment by Visgean** [comment]
https://www.lettingweb.com/

**Comment by Visgean** [comment]
https://www.gumtree.com/

**Comment by Visgean** [comment]
https://www.spareroom.co.uk/ only for 1 or 2 people

**Comment by Visgean** [comment]
http://www.zoopla.co.uk/

**Comment by qaisjp** [comment]
albeit useful, i think this might be beyond the scope of informatics

**Comment by Visgean** [comment]
its too late anyway.
